language: rust

rust:
  - stable
  - nightly

os:
  - linux
  - osx

dist: trusty
addons:
  apt:
    packages: libdbus-1-dev

script:
  - cargo build --features bluetooth-test
  - cargo test

notifications:
  webhooks: http://build.servo.org:54856/travis
